#!/bin/bash

declare -a cydia
cydia=($CYDIA)

echo "Restoring config";

if [ -f /tmp/weather.txt.tmp ];then 
	cp -f /tmp/weather.txt.tmp /Library/Themes/Typophone\ Weather.theme/weather.txt;
fi

exit 0