#!/bin/bash

declare -a cydia
cydia=($CYDIA)


echo "Restoring config";
if [ -f /tmp/weather.txt.tmp ];then 
	cp -f /tmp/weather.txt.tmp /Library/Themes/Typophone\ Weather.theme/weather.txt;
fi
if [ -f /tmp/background.css.tmp ];then
cp -f /tmp/background.css.tmp /Library/Themes/Typophone\ Weather.theme/background.css;
fi
if [ -f /tmp/background.css.tmp ];then
cp -f /tmp/custom.css.tmp /Library/Themes/Typophone\ Weather.theme/custom.css;
fi
if [ -f /tmp/app.css.tmp ];then
cp -f /tmp/app.css.tmp /Library/Themes/Typophone\ Weather.theme/app.css;
fi
if [ -f /tmp/LockBackground.jpg.tmp ];then
cp -f /tmp/LockBackground.jpg.tmp /Library/Themes/Typophone\ Weather.theme/LockBackground.jpg;
fi

exit 0