#!/bin/bash

declare -a cydia
cydia=($CYDIA)

echo "Backing up config";

if [ -f /Library/Themes/Typophone\ Weather.theme/weather.txt ];then 
	cp -f /Library/Themes/Typophone\ Weather.theme/weather.txt /tmp/weather.txt.tmp;
fi
if [ -f /Library/Themes/Typophone\ Weather.theme/background.css ];then
	cp -f /Library/Themes/Typophone\ Weather.theme/background.css /tmp/background.css.tmp;
fi
if [ -f /Library/Themes/Typophone\ Weather.theme/app.css ];then
	cp -f /Library/Themes/Typophone\ Weather.theme/app.css /tmp/app.css.tmp;
fi
if [ -f /Library/Themes/Typophone\ Weather.theme/custom.css ];then
	cp -f /Library/Themes/Typophone\ Weather.theme/custom.css /tmp/custom.css.tmp;
fi
if [ -f /Library/Themes/Typophone\ Weather.theme/LockBackground.jpg ];then
	cp -f /Library/Themes/Typophone\ Weather.theme/LockBackground.jpg /tmp/LockBackground.jpg.tmp;
fi

exit 0