#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [ -f /Library/Themes/Typophone\ Weather.theme/weather.txt ];then 
	cp -f /Library/Themes/Typophone\ Weather.theme/weather.txt /tmp/weather.txt.tmp
fi

exit 0